name: fishing_lab
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-102.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  mobx: ^2.1.4
  flutter_mobx: ^2.0.6+5
  dio: ^5.1.2
  provider: ^6.0.5
  synchronized: ^3.1.0
  equatable: ^2.0.5
  smooth_page_indicator: ^1.1.0
  shared_preferences: ^2.1.1
  uuid: ^3.0.7
  cupertino_icons: ^1.0.2

  google_sign_in: ^6.1.3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2

  location: ^4.2.0
  google_maps_flutter: ^2.2.8
  flutter_polyline_points: ^1.0.0
  url_launcher: ^6.1.11

  envied: ^0.3.0+3

  cached_network_image: ^3.2.3

  image_picker: ^0.8.7+5

  app_tracking_transparency: ^2.0.4

  sqflite: '2.2.8+3'

  intl: ^0.18.1
  cloud_firestore: '4.7.0'

  google_mobile_ads: ^3.0.0

  flutter_locales: '3.0.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner: ^2.3.3
  mobx_codegen: ^2.2.0

  flutter_lints: ^2.0.0
  envied_generator: ^0.3.0+3

  geolocator: ^9.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/locales/

  fonts:
    - family: BNR
      fonts:
        # - asset: assets/fonts/BebasNeue-Regular.ttf
        - asset: assets/fonts/Oswald-Medium.ttf
    - family: DNM
      fonts:
        - asset: assets/fonts/DMMono-Medium.ttf
    - family: MM
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: MR
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf