// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEwT1yxlbf0waFlIadVkSNZ0jsxFLcFrM',
    appId: '1:184421618342:web:3a2d720d6a68ab105b1a67',
    messagingSenderId: '184421618342',
    projectId: 'fishing-lab-project',
    authDomain: 'fishing-lab-project.firebaseapp.com',
    storageBucket: 'fishing-lab-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-HI9rlxoC_wbMvbaIwToxVJCBi7Sfy-8',
    appId: '1:184421618342:android:d26d2169f2cf359b5b1a67',
    messagingSenderId: '184421618342',
    projectId: 'fishing-lab-project',
    storageBucket: 'fishing-lab-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkdjFszSfvJXXbyUrJSeO4cobiR7qU8zA',
    appId: '1:184421618342:ios:51ba65efdb06b3725b1a67',
    messagingSenderId: '184421618342',
    projectId: 'fishing-lab-project',
    storageBucket: 'fishing-lab-project.appspot.com',
    iosClientId: '184421618342-4sn2as4blha99lhmq4ok9r03i690vsj3.apps.googleusercontent.com',
    iosBundleId: 'com.fishing.lab.exclusive.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkdjFszSfvJXXbyUrJSeO4cobiR7qU8zA',
    appId: '1:184421618342:ios:f570c7147417e8d55b1a67',
    messagingSenderId: '184421618342',
    projectId: 'fishing-lab-project',
    storageBucket: 'fishing-lab-project.appspot.com',
    iosClientId: '184421618342-9iqd40ubjubibm9lq496cnm6qgjgt30i.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishingLab.RunnerTests',
  );
}
